(ns lambda.core-test
  (:use [clojure.repl :only (source)])
  (:require [clojure.test :refer :all]
            [lambda.core :refer :all]))

(deftest a-test
  (testing "FIXME, I fail."
           (is (= (toI n0) 0))
           (is (= (toI n1) 1))
           (is (= (toI (S n3)) 4))
           (is (= (toI (n4 S n2)) 6))
           (is (= (toI (M n3 n2)) 6))
           (is (= (toB F) false))
           (is (= (toB (AND T T)) true))
           (is (= (toB (AND T F)) false))
           (is (= (toB (OR F T)) true))
           (is (= (toB (OR F F)) false))
           (is (= (toB (NOT F)) true))
           (is (= (toB (NOT T)) false))
           (is (= (toB (Z n0)) true))
           (is (= (toB (Z n4)) false))
           (is (= (toI (P n4)) 3))
           (is (= (toB (GE n4 n2)) true))
           (is (= (toB (GE n2 n4)) false))
           (is (= (toB (E n2 n4)) false))
           (is (= (toB (E n4 n4)) true))
;    (is (= (numcheck(S (S n2))) 4))
;    (is (= (numcheck(n4 S n2)) 6))
    ;(is (= (numcheck(M n3 n2)) 6))
  )
)
